export const FAQS = [
  { question: "What is Sanyuj?", answer: "Sanyuj is a local discovery app that brings together business offers, community announcements and nearby events. Use Offerly to explore promotions and Notify to keep up with neighbourhood updates, without creating an account." },
  { question: "How can I find local offers near me?", answer: "Open Offerly and select your pincode, locality or area in the filters. Choose a category and date range to narrow the available offers. Open an offer to check its details, validity and advertiser's terms." },
  { question: "Where can I find nearby events and local announcements?", answer: "Open Notify on Sanyuj to browse events, announcements and community updates for your selected area. Filter by category and date to find updates relevant to your neighbourhood." },
  { question: "How do I find offers and events for today or the next week?", answer: "Open Filters and choose Today, Tomorrow or Next 7 days in Date range. You can also choose custom start and end dates. The date filter includes items active during any part of the selected period. On the mobile filter panel, tap Apply to return to your results." },
  { question: "Do I need an account or location permission to use Sanyuj?", answer: "No account is needed to browse offers and local notifications. You can choose your pincode, locality or area manually without granting location permission. Phone notification permission is optional too." },
  { question: "How do I share a local business offer or community event?", answer: "Go to Share, select Offer or Notification, and open the relevant Google Form. Add the requested details so the Sanyuj team can review your submission and follow up. Submitting a request does not publish it automatically." },
  { question: "Why are there no offers or updates in my area?", answer: "There may be no published items matching your current area, category or dates. Try Any time, clear other filters or choose a wider area. Available content depends on what has been published for that location." },
  { question: "How can I report an incorrect offer or contact Sanyuj support?", answer: "Use the Contact Us form to ask a question, share feedback or report inaccurate information. Include the offer or announcement title, its link if available, and the details you would like the team to review." },
];
